# Generated by Django 5.1.2 on 2024-11-15 19:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events_app', '0001_initial'),
        ('profiles_app', '__first__'),
        ('projects_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в базу')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения в базе')),
                ('title', models.CharField(max_length=100)),
                ('type_notification', models.CharField(choices=[('for organizer', 'Для организатора'), ('for executor', 'Для исполнителя'), ('new contact', 'Вас добавили в контакт'), ('system', 'От системы'), ('for _', 'Для _')], default='system', max_length=20)),
                ('message', models.TextField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='profiles_app.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='profiles_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationNewContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в базу')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения в базе')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_contact', to='notifications.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в базу')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения в базе')),
                ('status', models.CharField(choices=[('accept', 'Заявка принята'), ('reject', 'Заявка отклонена'), ('consideration', 'Заявка на рассмотрении'), ('cancellation', 'Отмена заявки'), ('delete', '... удалено')], default='consideration', max_length=20)),
                ('is_organizer_to_participant', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_acceptance', to='events_app.eventspecificdate')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_acceptance', to='projects_app.project')),
                ('recipient_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_application', to='profiles_app.profile')),
                ('sender_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_application', to='profiles_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationForOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в базу')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения в базе')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_organizer', to='notifications.notification')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_organizer', to='notifications.statusapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationForExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в базу')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения в базе')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_executor', to='notifications.notification')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_executor', to='notifications.statusapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
