# Generated by Django 5.1.2 on 2024-11-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationNewContact',
        ),
    ]
