# Generated by Django 5.1.2 on 2024-11-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notificationforexecutor_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusapplication',
            old_name='event',
            new_name='specific_event',
        ),
    ]
