# Generated by Django 5.1.2 on 2024-11-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_event_statusapplication_specific_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusapplication',
            name='notifications',
        ),
        migrations.AddField(
            model_name='notificationforexecutor',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_executor', to='notifications.statusapplication'),
        ),
        migrations.AddField(
            model_name='notificationfororganizer',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_organizer', to='notifications.statusapplication'),
        ),
    ]
