# Generated by Django 5.1.2 on 2024-11-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notificationforexecutor_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusapplication',
            name='role',
            field=models.CharField(choices=[('organizer', 'Стать\\Пригласить организатором'), ('participant', 'Стать\\Пригласить участником')], default='Organizer', max_length=20),
        ),
    ]
