# Generated by Django 5.1.2 on 2024-11-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_statusapplication_role'),
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusapplication',
            name='recipient_application',
        ),
        migrations.AddField(
            model_name='statusapplication',
            name='recipient_application',
            field=models.ManyToManyField(related_name='recipient_application', to='profiles_app.profile'),
        ),
    ]
