# Generated by Django 5.1.2 on 2024-11-18 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
        ('notifications', '0010_alter_statusapplication_recipient_application'),
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusapplication',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_application', to='projects_app.project'),
        ),
        migrations.AlterField(
            model_name='statusapplication',
            name='specific_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_application', to='events_app.eventspecificdate'),
        ),
    ]
