# Generated by Django 5.1.2 on 2024-11-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_statusapplication_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('for organizer', 'Для организатор'), ('for participant', 'Для участника')], default='for participant', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('new contact', 'Вас добавили в контакт'), ('invitation', 'Приглашение'), ('cancellation', 'Отмена'), ('reminder', 'Напоминание'), ('system', 'От системы'), ('other', 'Другие')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='statusapplication',
            name='role',
            field=models.CharField(choices=[('organizer', 'Стать\\Пригласить организатором'), ('participant', 'Стать\\Пригласить участником')], default='organizer', max_length=20),
        ),
    ]
