# Generated by Django 5.1.2 on 2024-11-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_notification_recipient_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('for organizer', 'Для организатор'), ('for participant', 'Для участника'), ('for anyone', 'Для любого')], default='for anyone', max_length=20),
        ),
    ]
