# Generated by Django 5.1.2 on 2024-11-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_alter_notification_recipient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusapplication',
            name='status',
            field=models.CharField(choices=[('accept', 'Заявка принята'), ('reject', 'Заявка отклонена'), ('confirmed', 'Заявка подтверждена'), ('consideration', 'Заявка на рассмотрении'), ('cancellation', 'Отмена заявки'), ('delete', '... удалено')], default='consideration', max_length=20),
        ),
    ]
