# Generated by Django 5.1.2 on 2024-11-18 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в базу')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения в базе')),
                ('short_encrypted_id', models.CharField(max_length=64, unique=True)),
                ('max_clicks', models.PositiveIntegerField(default=0)),
                ('current_clicks', models.PositiveIntegerField(default=0)),
                ('type_link', models.CharField(choices=[('contact', 'Добавление в контакты'), ('event', 'Cсылка в событие'), ('project', 'Cсылка в проект')], default='contact', max_length=20)),
                ('role', models.CharField(blank=True, choices=[('organizer', 'Пригласить организатором'), ('participant', 'Пригласить участником')], default='participant', max_length=20, null=True)),
                ('resource_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
