# Generated by Django 5.1.2 on 2024-11-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_links_app', '0003_alter_limitedlink_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitedlink',
            name='profile',
        ),
    ]
