# Generated by Django 5.1.2 on 2024-11-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_links_app', '0005_limitedlink_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitedlink',
            name='short_encrypted_id',
        ),
    ]
