# Generated by Django 5.1.2 on 2024-11-19 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_links_app', '0006_remove_limitedlink_short_encrypted_id'),
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limitedlink',
            old_name='type_link',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='limitedlink',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='profiles_app.profile'),
        ),
    ]
