# Generated by Django 5.1.2 on 2024-11-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_links_app', '0007_rename_type_link_limitedlink_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedlink',
            name='short_encrypted_id',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
