# Generated by Django 5.1.2 on 2024-11-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_links_app', '0008_limitedlink_short_encrypted_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedlink',
            name='short_encrypted_id',
            field=models.TextField(unique=True),
        ),
    ]
