# Generated by Django 5.1.2 on 2024-11-15 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в базу')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения в базе')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('access', models.CharField(choices=[('all', 'For all'), ('me', 'Only me')], default='all', max_length=20)),
                ('reminder_delta', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=100)),
                ('personal_note', models.TextField(blank=True, max_length=100)),
                ('organizers', models.ManyToManyField(blank=True, related_name='project_organizers', to='profiles_app.profile')),
                ('participants', models.ManyToManyField(blank=True, related_name='project_participants', to='profiles_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
