# Generated by Django 5.1.2 on 2024-11-21 15:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0007_alter_personallinks_profile'),
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='personal_note',
        ),
        migrations.AddField(
            model_name='project',
            name='is_need_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='profiles_app.profile'),
        ),
        migrations.CreateModel(
            name='PersonalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в базу')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения в базе')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_note', to='profiles_app.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_note', to='projects_app.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
