# Generated by Django 5.1.2 on 2024-11-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_remove_project_personal_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnote',
            name='note',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
