# Generated by Django 5.1.2 on 2024-11-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
