# Generated by Django 5.1.2 on 2024-11-21 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_event_is_personal_event_photo'),
        ('profiles_app', '0007_alter_personallinks_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_owner', to='profiles_app.profile'),
        ),
    ]
