# Generated by Django 5.1.2 on 2024-11-21 21:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_event_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecurring',
            name='excluded_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None),
        ),
    ]
