# Generated by Django 5.1.2 on 2024-11-22 10:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_eventrecurring_excluded_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrecurring',
            name='custom_period',
        ),
        migrations.RemoveField(
            model_name='eventrecurring',
            name='weekly_days',
        ),
        migrations.AddField(
            model_name='eventrecurring',
            name='custom_period_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='eventrecurring',
            name='weekly_days_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
