# Generated by Django 5.1.2 on 2024-11-22 13:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0005_remove_eventrecurring_custom_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecurring',
            name='custom_period_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='eventrecurring',
            name='excluded_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None),
        ),
    ]
