# Generated by Django 5.1.2 on 2024-11-22 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0006_alter_eventrecurring_custom_period_array_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventrecurring',
            old_name='excluded_days',
            new_name='excluded_days_array',
        ),
    ]
