# Generated by Django 5.1.2 on 2024-11-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0007_rename_excluded_days_eventrecurring_excluded_days_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventspecificdate',
            name='personal_note',
        ),
    ]
