# Generated by Django 5.1.2 on 2024-11-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0008_remove_eventspecificdate_personal_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecurring',
            name='recurring_type',
            field=models.CharField(choices=[('one-time', 'Единоразово'), ('monthly', 'Ежемесячно'), ('weekly', 'Еженедельно'), ('two-weekly', 'Двухнедельный режим'), ('yearly', 'Раз в год'), ('daily', 'Раз в день'), ('custom', 'Настраиваемый')], max_length=10),
        ),
    ]
