# Generated by Django 5.1.2 on 2024-12-02 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('events_app', '0009_alter_eventrecurring_recurring_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPeriodicTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
                ('event_recurring', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodic_task', to='events_app.eventrecurring')),
                ('event_specific', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_task', to='events_app.eventspecificdate')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
