# Generated by Django 5.1.2 on 2024-12-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0010_eventperiodictask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_reminder',
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
