# Generated by Django 5.1.2 on 2024-11-15 19:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в базу')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения в базе')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='surname')),
                ('is_closed', models.BooleanField(default=False, verbose_name='closed')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('telegram', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телеграм')),
                ('info', models.TextField(blank=True, max_length=300, verbose_name='Информация о себе')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Введите корректный адрес электронной почты')], verbose_name='Почта')),
                ('personal_link', models.URLField(blank=True, verbose_name='Моя ссылка')),
                ('contacts', models.ManyToManyField(blank=True, to='profiles_app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в базу')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения в базе')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_links', to='profiles_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в базу')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения в базе')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_level', to='profiles_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
