# Generated by Django 5.1.2 on 2024-11-20 10:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в базу')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения в базе')),
                ('is_dark_mode', models.BooleanField(default=True)),
                ('is_search_by_nickname', models.BooleanField(default=False)),
                ('is_warning_about_upcoming_events', models.BooleanField(default=False)),
                ('is_name', models.BooleanField(default=False)),
                ('is_about_me', models.BooleanField(default=False)),
                ('is_phone', models.BooleanField(default=False)),
                ('is_link_to_telegram', models.BooleanField(default=False)),
                ('is_email', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='profiles_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в базу')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения в базе')),
                ('is_from_app', models.BooleanField(default=True)),
                ('is_reminder_about_event', models.BooleanField(default=True)),
                ('is_user_confirmed_event', models.BooleanField(default=True)),
                ('is_invite_to_schedule', models.BooleanField(default=True)),
                ('is_invite_to_event', models.BooleanField(default=True)),
                ('is_change_in_event', models.BooleanField(default=True)),
                ('is_cancellation_event', models.BooleanField(default=True)),
                ('is_new_open_event', models.BooleanField(default=True)),
                ('is_new_application', models.BooleanField(default=True)),
                ('is_project_change_in_event', models.BooleanField(default=True)),
                ('is_user_refused_to_participate', models.BooleanField(default=True)),
                ('is_user_left_project', models.BooleanField(default=True)),
                ('is_user_joined_project', models.BooleanField(default=True)),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='profiles_app.profilesettings')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
