# Generated by Django 5.1.2 on 2024-11-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0002_profilesettings_notificationsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='profile',
            name='safety',
            field=models.CharField(choices=[('open', 'Открытый профиль'), ('partial', 'Частичная информация'), ('closed', 'Закрытый профиль')], default='open', max_length=20),
        ),
    ]
