# Generated by Django 5.1.2 on 2024-11-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0003_remove_profile_is_closed_profile_safety'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
