# Generated by Django 5.1.2 on 2024-11-21 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0006_rename_user_accesslevel_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personallinks',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_links', to='profiles_app.profile'),
        ),
    ]
