# Generated by Django 5.1.2 on 2024-11-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0007_alter_personallinks_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_contacts',
            field=models.ManyToManyField(blank=True, related_name='in_blocked_contacts', to='profiles_app.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='in_contacts', to='profiles_app.profile'),
        ),
    ]
