# Generated by Django 5.1.2 on 2024-11-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0008_profile_blocked_contacts_alter_profile_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalLinks',
        ),
    ]
