# Generated by Django 5.1.2 on 2024-11-27 22:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0009_delete_personallinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=5),
        ),
    ]
