# Generated by Django 5.1.2 on 2024-11-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0008_remove_eventspecificdate_personal_note'),
        ('profiles_app', '0010_profile_personal_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_events',
            field=models.ManyToManyField(blank=True, related_name='selected_events', to='events_app.eventspecificdate'),
        ),
    ]
